### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by AlbertoJaenal** [luigifreda/pyslam#125]
Hi, Luigi!
Thanks for this nice repo! It is working well and it is really nice to have such many implmented features to try!
I just have been working a little with this repo and have some suggestions that you may take into account for next updates:

- Just for clarity, I think you can move all the implemented features and the implemented loop closures to folders, so that the main folder is not filled with so many files. I already managed to do this, at it was not so invasive.
-  Same with the installation files (.sh) and maybe the utils. I think just having the main parts of the SLAM pipeline in the main folder will make it more easy to navigate!
- So I have been trying to relocalize MH02 on a map created with MH01, and got this behaviour:
![image](https://github.com/user-attachments/assets/96dbc335-a0ec-4d4c-bbf3-e06a7cb9709b)
I was wondering that maybe, if the pipeline was able to localize and got lost again at some point, instead of plotting just 0, it could just follow the VO trajectory until it gets relocalized again. This behavious is more realistic at least for me.

I will keep working on this. If I have more ideas/suggestion/additions, I will write to you or make some pull request.

**Comment by luigifreda** [comment]
Hi Alberto,

Thank you for your feedback!
Reorganizing the files into folders and refactoring are indeed on my TODO list, and they’re already in progress.

Regarding your observation on relocalization, I’d like to clarify:
> I was wondering that maybe, if the pipeline was able to localize and got lost again at some point, instead of plotting just 0, it could just follow the VO trajectory until it gets relocalized again. This behavious is more realistic at least for me.

When VO gets lost, it’s not possible to “just follow the VO trajectory until it gets relocalized again” because VO itself is lost (by assumption). 
Did you mean reinitializing in the meantime and then merging the maps once relocalization occurs, as in ORBSLAM3? If so, this is also on my (long!) TODO list. 😊 However, implementing multimap management would require a fair amount of additional work.

If you’d like to contribute, I’d be thrilled to consider further suggestions and pull requests. 

Cheers,
Luigi

**Comment by AlbertoJaenal** [comment]
Hi, thanks for your answers! Looking forward to your new updates.
Meanwhile, I will post here the problems that I have found so far (I cannot push code).

- Replace these two lines (https://github.com/luigifreda/pyslam/blob/0c8aa8faaccb8528970ab7d2040011b883fef784/feature_matcher.py#L439-L440) for (it raises an error in the empty case because empty arrays are float by default)
 ```
            result.idxs1 = idxs1.astype(np.int64)
            result.idxs2 = idxs2.astype(np.int64)         
```
- On issue that I found is that each global descriptor is computed twice (first when the `run_task` function is called in the loop_detector_X) and then, again in the covisible loop in the `compute_reference_similarity_score` in loop_detector_base. And you can check this by checking if the covisible keyframes have a g_des assigned when the `add_keyframe` method is called in loop_cloosing, for example adding just after or before this (https://github.com/luigifreda/pyslam/blob/0c8aa8faaccb8528970ab7d2040011b883fef784/loop_closing.py#L745):
 ```
                print([(x.id, x.g_des is None) for x in covisible_keyframes])
 ```
You will see that the last keyframe added has not g_des assigned, so somehow it is not stored properly the first time that it is computed. This is not nice because it takes twice time and resources, and for deep descriptors could be even worse.

**Comment by luigifreda** [comment]
Hi Alberto,

Thank you for your feedback!

- I’ve never encountered an error related to those two lines in the feature matcher file, but I’ve added them as suggested. Thanks for pointing it out.

- Regarding the double computation of `g_des` (global descriptor) that you noticed, I investigated the issue further. I found the first keyframe (created during the initialization stage) is not stored with an associated image. This leads to the compute_reference_similarity_score() function attempting to compute `g_des` multiple times whenever the keyframe is part of the current "covisible island." Specifically, the function tries to compute `g_des`, but the computation is skipped because the required image is missing from the first keyframe. This behavior only occurs with loop detectors that rely on an image to calculate the global descriptor.
I’ve pushed and implemented some improvements to ensure that the first keyframe now stores an image properly. You can verify that there is no double computation of g_des by running:
```bash
tail -f logs/loop_closing.log logs/loop_detecting.log
```
and observing the lines that state: *** computing global descriptor ***.

Let me know if you need further clarification or assistance!

Best,
Luigi
