### ISSUE TITLE
Manual install procedure is not documented

### ISSUE THREAD

**Issue by Matthew-Bradley** [luigifreda/pyslam#45]
Greetings,

I am trying to install and run pyslam in a shared university environment, for a course.

I have the ability to create python virtual environments, install packages in them, the ability to compile software, as well as basic operations like downloading from git repos. This environment is also the only place I have access to computational/GPU resources to run pytorch and tensorflow.

However, this environment is not running ubuntu 18.04 nor am I allowed to install system packages. As a result, the install scripts cannot be run.

These scripts are nested and very complex, and I am finding it difficult to trace many of the actions they perform in order to satisfy pyslam's dependencies.

Is it possible you could provide an equivalent list of all the manual steps required to set up pyslam's dependencies? Which steps may not be required, depending on the desired feature detector and descriptor?

Thank you very much for your help,
    -Matthew Bradley

**Comment by luigifreda** [comment]
Hi Matthew, 
thank you very much for your feedback. 

I am not 100% sure you can actually install pyslam in such a shared university environment, without having the possibility to install system packages that are required as dependencies. 
Indeed, I worked very hard in order to prepare and share the install scripts in my free time and I am still working hard in order to improve the install scripts. 
Moreover, such scripts are also thought to provide a practical guide for people that want to tweak/customize them. As you can understand, there are many deps and the OSs are continuing to evolve: even thinking about a general manual procedure, I am not sure this can remain valid for a pair of months or so. 

In any case, as reported in the main README, I provided an install procedure that creates a new virtual environment pyslam: you can easily launch the scripts described here: https://github.com/luigifreda/pyslam/blob/master/PYTHON-VIRTUAL-ENVS.md 
You can try to jump the installation of the system packages by providing a manual replacement for them. To this aim, you can add an immediate exit in the script `install_system_packages.sh` and replace the `install_package()` in the file `bash_utils.sh` with an empty function.
