### ISSUE TITLE
Curiosity: Fuzzy Image Matching?

### ISSUE THREAD

**Issue by BrandonKMLee** [luigifreda/pyslam#62]
There are multiple fuzzy full image matching https://github.com/thorn-oss/perception
When making it Transform-Invariant some has used triangle meshes https://pippy360.github.io/transformationInvariantImageSearch/
But as seen with this repo, there is an alternative https://github.com/luigifreda/pyslam#-supported-local-features
e.g.
- https://all4win.github.io/projects/cv_proj2/index.html
- https://cclaassen3.github.io/computer-vision-local-feature-matching/

Are there any algorithms that are included in this repo that does something similar?

**Comment by luigifreda** [comment]
In this repo, you can find a collection of detectors/descriptors that allow matching local features (pixel regions) over two or more images depicting the same scene. This process allows estimating the geometric relationship between the cameras that produced the images. This is crucial for SLAM techniques. 
I suggest taking a look at this short article https://ducha-aiki.github.io/wide-baseline-stereo-blog/2020/03/27/intro.html 

These are the basic steps (as you found in the other linked articles)
![local-features-matching-filtering](https://user-images.githubusercontent.com/10080262/135769642-e466301e-9855-444c-b73a-22df252bb799.png)

You can use the file [test/cv/test_feature_matching.py ](https://github.com/luigifreda/pyslam/blob/master/test/cv/test_feature_matching.py) in order to play with some of the local features available in this repo. Some of them work as expected with great resilience to different perspective transformations. Others are less exciting. For instance, ROOT_SIFT, SUPERPOINT, CONTEXTDESC, LFNET, KEYNET work really nice in many contexts. 

A different approach is used for the place recognition problem (another form of image matching). In general, this is managed by using the perceptual hashing approach, moving at a higher level from local feature descriptors to global image descriptors. Typically, this requires a further geometric validation step to actually confirm and sort out a valid match from a set of candidates.  

Hope this helps. 

P.S.: a nice talk on the subject https://www.youtube.com/watch?v=ZscK5p9hZBI
