### ISSUE TITLE
What are good parameters for VO?

### ISSUE THREAD

**Issue by antopost** [luigifreda/pyslam#87]
I want to evaluate some keypoint detectors for VO, but all detectors use the same [parameters](https://github.com/luigifreda/pyslam/blob/5e860f0e22c3673dae19c4d52e6cb40f968ce9e7/visual_odometry.py#L33) in `visual_odometry.py`.

I believe each keypoint detector will have its own set of ideal parameters.
Has anyone done some testing in this regard?

**Comment by luigifreda** [comment]
Hi,
thanks for your feedback. I agree with you. Local features are just a part of the system. In general, many related parameters should be properly tuned according to the adopted local features and matcher since the data association error statistics (and other implied data distribution models) change over the different choices. 
As for the `main_slam.py` subsystem, there are these other parameters too:
https://github.com/luigifreda/pyslam/blob/5e860f0e22c3673dae19c4d52e6cb40f968ce9e7/parameters.py 

Fine-tuning such parameters is a black magic art and does require a proper evaluation SW to support the analysis and the tuning itself. This is something to add to the TODO list.  

Please, if you run your evaluations on pyslam VO, recall this important note
![Screenshot from 2023-10-14 17-04-31](https://github.com/luigifreda/pyslam/assets/10080262/7e31b44a-21b5-475d-a103-c687d1e5e837)

Please, let me know if you have any plans in this regard. 
Cheers,
Luigi
